name: CI Checks
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: Get origin master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@main
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  lint:
    runs-on: ${{ matrix.os }}

    needs: [setup]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: Get origin master
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@main
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On Master (Linux)
        if: github.event_name == 'push' && runner.os == 'Linux'
        run: yarn affected:lint --base=$GITHUB_REF~1 --head=$GITHUB_SHA --parallel
      - name: Run On Master (Windows)
        if: github.event_name == 'push' && runner.os == 'Windows'
        run: yarn affected:lint --base=${env:GITHUB_REF}~1 --head=${env:GITHUB_SHA} --parallel
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:lint --base=origin/master --head=HEAD --parallel

  build:
    runs-on: ${{ matrix.os }}

    needs: [setup]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: Get origin master
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@main
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On Master (Linux)
        if: github.event_name == 'push' && runner.os == 'Linux'
        run: yarn affected:build --base=$GITHUB_REF~1 --head=$GITHUB_SHA --parallel
      - name: Run On Master (Windows)
        if: github.event_name == 'push' && runner.os == 'Windows'
        run: yarn affected:build --base=${env:GITHUB_REF}~1 --head=${env:GITHUB_SHA} --parallel
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:build --base=origin/master --head=HEAD --parallel

  test:
    runs-on: ${{ matrix.os }}

    needs: [setup]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: Get origin master
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@main
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On Master (Linux)
        if: github.event_name == 'push' && runner.os == 'Linux'
        run: yarn affected:test --base=$GITHUB_REF~1 --head=$GITHUB_SHA --parallel
      - name: Run On Master (Windows)
        if: github.event_name == 'push' && runner.os == 'Windows'
        run: yarn affected:test --base=${env:GITHUB_REF}~1 --head=${env:GITHUB_SHA} --parallel
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:test --base=origin/master --head=HEAD --parallel
